// napcat.webui/src/pages/network/HttpClientComponent.vue
<template>
    <div>
        <t-form labelAlign="left">
            <t-form-item label="启用">
                <t-switch v-model="props.config.data.enable" />
            </t-form-item>
            <t-form-item label="URL">
                <t-input v-model="props.config.data.url" />
            </t-form-item>
            <t-form-item label="消息格式">
                <t-select v-model="props.config.data.messagePostFormat" :options="messageFormatOptions" />
            </t-form-item>
            <t-form-item label="报告自身消息">
                <t-switch v-model="props.config.data.reportSelfMessage" />
            </t-form-item>
            <t-form-item label="Token">
                <t-input v-model="props.config.data.token" />
            </t-form-item>
            <t-form-item label="调试模式">
                <t-switch v-model="props.config.data.debug" />
            </t-form-item>
        </t-form>
    </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { HttpClientConfig } from '../../../../src/onebot/config/config';

const defaultConfig: HttpClientConfig = {
    name: 'http-client',
    enable: false,
    url: 'http://localhost:8080',
    messagePostFormat: 'array',
    reportSelfMessage: false,
    token: '',
    debug: false,
};

const props = defineProps<{
    config: { data: HttpClientConfig };
}>();

props.config.data = { ...defaultConfig, ...props.config.data };

const messageFormatOptions = ref([
    { label: 'Array', value: 'array' },
    { label: 'String', value: 'string' },
]);

watch(
    () => props.config.data.messagePostFormat,
    (newValue) => {
        if (newValue !== 'array' && newValue !== 'string') {
            props.config.data.messagePostFormat = 'array';
        }
    }
);
</script>

<style scoped></style>

// napcat.webui/src/components/network_edit/http_client.tsx
import GenericForm from './generic_form'
import type { Field } from './generic_form'

export interface HTTPClientFormProps {
  data?: OneBotConfig['network']['httpClients'][0]
  onClose: () => void
  onSubmit: (data: OneBotConfig['network']['httpClients'][0]) => Promise<void>
}

type HTTPClientFormType = OneBotConfig['network']['httpClients']

const HTTPClientForm: React.FC<HTTPClientFormProps> = ({
  data,
  onClose,
  onSubmit
}) => {
  const defaultValues: HTTPClientFormType[0] = {
    enable: false,
    name: '',
    url: 'http://localhost:8080',
    reportSelfMessage: false,
    messagePostFormat: 'array',
    token: '',
    debug: false
  }

  const fields: Field<'httpClients'>[] = [
    {
      name: 'enable',
      label: '启用',
      type: 'switch',
      description: '保存后启用此配置',
      colSpan: 1
    },
    {
      name: 'debug',
      label: '开启Debug',
      type: 'switch',
      description: '是否开启调试模式',
      colSpan: 1
    },
    {
      name: 'name',
      label: '名称',
      type: 'input',
      placeholder: '请输入名称',
      isRequired: true,
      isDisabled: !!data
    },
    {
      name: 'url',
      label: 'URL',
      type: 'input',
      placeholder: '请输入URL',
      isRequired: true
    },
    {
      name: 'reportSelfMessage',
      label: '上报自身消息',
      type: 'switch',
      description: '是否上报自身消息',
      colSpan: 1
    },
    {
      name: 'messagePostFormat',
      label: '消息格式',
      type: 'select',
      placeholder: '请选择消息格式',
      isRequired: true,
      options: [
        { key: 'array', value: 'Array' },
        { key: 'string', value: 'String' }
      ],
      colSpan: 1
    },
    {
      name: 'token',
      label: 'Token',
      type: 'input',
      placeholder: '请输入Token'
    }
  ]

  return (
    <GenericForm
      data={data}
      defaultValues={defaultValues}
      onClose={onClose}
      onSubmit={onSubmit}
      fields={fields}
    />
  )
}

export default HTTPClientForm
