// packages/napcat-webui-frontend/src/components/network_edit/http_server.tsx
import GenericForm, { random_token } from './generic_form';
import type { Field } from './generic_form';

export interface HTTPServerFormProps {
  data?: OneBotConfig['network']['httpServers'][0]
  onClose: () => void
  onSubmit: (data: OneBotConfig['network']['httpServers'][0]) => Promise<void>
}

type HTTPServerFormType = OneBotConfig['network']['httpServers'];

const HTTPServerForm: React.FC<HTTPServerFormProps> = ({
  data,
  onClose,
  onSubmit,
}) => {
  const defaultValues: HTTPServerFormType[0] = {
    enable: false,
    name: '',
    host: '127.0.0.1',
    port: 3000,
    enableCors: true,
    enableWebsocket: true,
    messagePostFormat: 'array',
    token: random_token(16),
    debug: false,
  };

  const fields: Field<'httpServers'>[] = [
    {
      name: 'enable',
      label: '启用',
      type: 'switch',
      description: '保存后启用此配置',
      colSpan: 1,
    },
    {
      name: 'debug',
      label: '开启Debug',
      type: 'switch',
      description: '是否开启调试模式',
      colSpan: 1,
    },
    {
      name: 'name',
      label: '名称',
      type: 'input',
      placeholder: '请输入名称',
      isRequired: true,
      isDisabled: !!data,
    },
    {
      name: 'host',
      label: 'Host',
      type: 'input',
      placeholder: '请输入主机地址',
      isRequired: true,
    },
    {
      name: 'port',
      label: 'Port',
      type: 'input',
      placeholder: '请输入端口',
      isRequired: true,
    },
    {
      name: 'enableCors',
      label: '启用CORS',
      type: 'switch',
      description: '是否启用CORS跨域',
      colSpan: 1,
    },
    {
      name: 'enableWebsocket',
      label: '启用Websocket',
      type: 'switch',
      description: '是否启用Websocket',
      colSpan: 1,
    },
    {
      name: 'messagePostFormat',
      label: '消息格式',
      type: 'select',
      placeholder: '请选择消息格式',
      isRequired: true,
      options: [
        { key: 'array', value: 'Array' },
        { key: 'string', value: 'String' },
      ],
    },
    {
      name: 'token',
      label: 'Token',
      type: 'input',
      placeholder: '请输入Token',
    },
  ];

  return (
    <GenericForm
      data={data}
      defaultValues={defaultValues}
      onClose={onClose}
      onSubmit={onSubmit}
      fields={fields}
    />
  );
};

export default HTTPServerForm;

// napcat.webui/src/pages/network/HttpServerComponent.vue
<template>
    <div>
        <t-form labelAlign="left">
            <t-form-item label="启用">
                <t-switch v-model="props.config.data.enable" />
            </t-form-item>
            <t-form-item label="端口">
                <t-input v-model.number="props.config.data.port" type="number" />
            </t-form-item>
            <t-form-item label="主机">
                <t-input v-model="props.config.data.host" type="text" />
            </t-form-item>
            <t-form-item label="启用 CORS">
                <t-switch v-model="props.config.data.enableCors" />
            </t-form-item>
            <t-form-item label="启用 WS">
                <t-switch v-model="props.config.data.enableWebsocket" />
            </t-form-item>
            <t-form-item label="消息格式">
                <t-select v-model="props.config.data.messagePostFormat" :options="messageFormatOptions" />
            </t-form-item>
            <t-form-item label="Token">
                <t-input v-model="props.config.data.token" type="text" />
            </t-form-item>
            <t-form-item label="调试模式">
                <t-switch v-model="props.config.data.debug" />
            </t-form-item>
        </t-form>
    </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { HttpServerConfig } from '../../../../src/onebot/config/config';

const defaultConfig: HttpServerConfig = {
    name: 'http-server',
    enable: false,
    port: 3000,
    host: '0.0.0.0',
    enableCors: true,
    enableWebsocket: true,
    messagePostFormat: 'array',
    token: '',
    debug: false,
};

const props = defineProps<{
    config: { data: HttpServerConfig };
}>();

props.config.data = { ...defaultConfig, ...props.config.data };

const messageFormatOptions = ref([
    { label: 'Array', value: 'array' },
    { label: 'String', value: 'string' },
]);

watch(
    () => props.config.data.messagePostFormat,
    (newValue) => {
        if (newValue !== 'array' && newValue !== 'string') {
            props.config.data.messagePostFormat = 'array';
        }
    }
);
</script>

<style scoped></style>
